
stages:
    - check
    - test
    - deploy
    
cache:
  paths:
    - vendor/

phplint:
    stage: check
    image: cyberpearuk/php-build-docker
    script: phplint --exclude=vendor ./

phpcs:
    stage: check
    image: cyberpearuk/php-build-docker
    script:
        - composer global config http-basic.nexus.jbuncle.co.uk composer-publisher $NEXUS_PASS 
        - composer install
        - vendor/bin/phpcs -n -s --standard=php-standards ./src
        - vendor/bin/phpcs -n -s --standard=php-standards ./tests

phan:
    stage: check
    image: cyberpearuk/php-build-docker
    script:
        - composer global config http-basic.nexus.jbuncle.co.uk composer-publisher $NEXUS_PASS 
        - composer install --no-dev
        - phan --target-php-version=7.1
        - phan --target-php-version=7.2
        - phan --target-php-version=7.3
        - phan --target-php-version=7.4

phpunit:
    stage: test
    image: cyberpearuk/php-build-docker
    script:
        - composer global config http-basic.nexus.jbuncle.co.uk composer-publisher $NEXUS_PASS 
        - composer install
        - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never
    coverage: '/^\s*Lines:\s*\d+.\d+\%/'

tag:
    stage: deploy
    image: docker.jbuncle.co.uk/jbuncle/php-autosemver
    script:
        - tag
    only:
        refs:
            - master

deploy_tag:
    stage: deploy
    image: jbuncle/composer-nexus-upload
    script:
        - nexus-upload
         --repository=https://nexus.jbuncle.co.uk/repository/composer-private/ 
         --username=composer-publisher 
         --password=$NEXUS_PASS 
         --version=$CI_COMMIT_TAG
         --ignore="/^(nbproject.*|\.gitlab\-ci\.yml|\.phan.*|tests.*|phpunit\.xml)$/"
    only:
        - tags

